
[terminal.shell]
program               = "/usr/bin/zsh"
args                  = [ "--login", ]

#working_directory     = "None"
#live_config_reload    = true
#ipc_socket            = true

[env]
TERM                  = "xterm-256color"


[scrolling]
history               = 65535
#multiplier            = 3

[font]
normal                = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold                  = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic                = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic           = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
#size                  = 11.25
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }

[general]
# alacritty.toml
# commented lines are the defaults
# man 5 alacritty (>0.13) for full config manual

import = [
"~/.config/alacritty/mocha.toml"
]

[terminal]
#builtin_box_drawing   = true

